@startuml

skinparam shadowing false
left to right direction
'skinparam monochrome true

frame "トップ画面" as p001 <<FP001>>
frame "顧客ログイン画面" as p002 <<FP002>>
note right: ログイン成功時は\nログイン前の画面に戻る
frame "顧客アカウント登録\n(入力)画面" as p003 <<FP003>>
frame "顧客アカウント登録\n(確認)画面" as p004 <<FP004>>
frame "顧客アカウント登録\n(完了)画面" as p005 <<FP005>>
frame "カテゴリ別\n商品検索画面" as p006 <<FP006>>
frame "商品詳細画面" as p007 <<FP007>>
frame "購入(入力)画面" as p008 <<FP008>>
frame "購入(確認)画面" as p009 <<FP009>>
frame "購入(完了)画面" as p010 <<FP010>>
frame "購入履歴\n一覧画面" as p011 <<FP011>>
frame "購入履歴\n詳細画面" as p012 <<FP012>>

interface start

start --> p001
p001 --> p002: ログイン
p001 --> p003: 顧客アカウント\n登録
p003 --> p004: 送信
p004 --> p005: 完了
p001 --> p006: 商品検索
p006 --> p007: 商品選択
p001 --> p007: 商品選択
p007 --> p008: 購入
p008 --> p009: 購入確認
p001 --> p009: カート
p009 --> p010: 購入確定
p001 <-- p010: トップに戻る
p011 <-- p010: 購入履歴
p001 --> p011: 購入履歴
p011 --> p012

' p002 --> p002 : ログイン失敗
' p002 -ri-> p001_after : ログイン成功
' p001_after -le-> p001_before : ログアウト

' p001_after --> p015 : 購入履歴
' p015 --> p016

' p001_after --> p006 : 商品情報メンテナンス
' p001_after --> p003 : アカウント登録
' p001_after --> p019 : 商品カテゴリ登録

' p019 --> p019 : 入力エラー
' p019 --> p020 : 確認
' p019 <-- p020 : 戻る
' p020 --> p021 : 登録
' p021 --> p019 : 入力に戻る
' p021 --> p001_after : 業務終了

' p003 --> p003 : 入力エラー
' p003 --> p004 : 確認
' p003 <-- p004 : 戻る
' p004 --> p005 : 登録
' p005 --> p003 : 入力に戻る
' p005 --> p001_after : 業務終了

' p006 --> p012 : 商品登録
' p012 --> p012 : 入力エラー
' p012 --> p013 : 確認
' p012 <-- p013 : 戻る
' p013 --> p014 : 登録
' p014 --> p006 : 商品検索に戻る
' p014 --> p012 : 入力に戻る
' p014 --> p001_after : 業務終了

' p006 --> p009 : 商品修正
' p009 --> p009 : 入力エラー
' p009 --> p010 : 確認
' p009 <-- p010 : 戻る
' p010 --> p011 : 修正
' p011 --> p006 : 商品検索に戻る
' p011 --> p001_after : 業務終了

' p006 --> p007 : 商品削除
' p006 <-- p007 : キャンセル
' p007 --> p008 : 削除
' p008 --> p006 : 商品検索に戻る
' p008 --> p001_after : 業務終了

' p001_after --> p016 : 配送手続き
' p016 --> p016 : 入力エラー
' p016 --> p017 : 確認
' p016 <-- p017 : 戻る
' p017 --> p018 : 登録
' p018 --> p016 : 入力に戻る
' p018 --> p001_after : 業務終了
@enduml