name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports/allure-report/allureReport
      # - uses: actions/checkout@v2
      # - name: Set up JDK 11
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: '11'
      #     distribution: 'adopt'
      # - name: Grant execute permission for gradlew
      #   run: chmod +x gradlew
      # - name: Build,Test with Gradle
      #   run: ./gradlew allureReport --depends-on-tests
      # - name: Allure Report with history
      #   uses: simple-elf/allure-report-action@v1.6
      #   if: always()
      #   id: allure-report
      #   with:
      #     allure_results: build/allure-results
      #     gh_pages: gh-pages
      #     allure_report: allure-report
      #     allure_history: allure-history